name: Build
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    env:
      SLN_FILE_NAME: Digitalroot.Valheim.Dungeons.sln
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.1
        with:
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Add BepInEx NuGet Source
        run: nuget sources add -name "BepInEx" -Source https://nuget.bepinex.dev/v3/index.json
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Restore packages
        run: nuget restore ${{ github.workspace }}/src/${{ env.SLN_FILE_NAME }}
      - name: Build Odin's Hollow
        run: dotnet build ${{ github.workspace }}/src/${{ env.SLN_FILE_NAME }} -c Release --no-restore
      - name: Rename
        uses: Amadevus/pwsh-script@v2.0.1
        id: rename-zip
        with:
          script: Get-ChildItem ${{ github.workspace }}/src/Digitalroot.Valheim.Dungeons.OdinsHollow/bin/*.zip | Rename-Item -NewName { $_.Name -replace '.zip','.${{ github.run_id }}.zip' }
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/src/Digitalroot.Valheim.Dungeons.OdinsHollow/bin/*.zip
          name: Build-Artifacts
          retention-days: 1
